name: TheVitalityTest
favicon: null
layout_spectrum: 0.08607227890752256
typography_spectrum: 0.3770053945481777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7446481352671981
  lightness: 0.000055988552048802376
  saturation: 0.06824515108019114
  rhythmicContrast: 0.3426608392037451
purpose: []
